### ISSUE TITLE
Typescript compilation errors when using the specific action in a reducer matching case

### ISSUE THREAD

**Issue by bluEEil** [ngrx/example-app#176]
I'm working on a project which I can't post online, I'm facing compilation errors when working with typescript 2.4.1 and ngrx4. 

I already written a more detailed question in stackoverflow (It also has a bounty on it :):
[Detailed question (I recommend reading the info there and not here though its longer)](https://stackoverflow.com/questions/46264002/ngrx-payload-in-reducer-action-not-compilling)

Here's a smaller example and explanation of what i'm trying to code: (based on this example app)

`export function reducer(state = initialState, action: book.Actions | collection.Actions): State {
  switch (action.type) {
    case collection.LOAD_SUCCESS: {
      const books = action.payload;
      const newBooks = books.filter(book => !state.entities[book.id]);

      const newBookIds = newBooks.map(book => book.id);
      const newBookEntities = newBooks.reduce((entities: { [id: string]: Book }, book: Book) => {
        return Object.assign(entities, {
          [book.id]: book
        });
      }, {});

      return {
        ids: [ ...state.ids, ...newBookIds ],
        entities: Object.assign({}, state.entities, newBookEntities),
        selectedBookId: state.selectedBookId
      };
    }`

This code is taken from the book reducer in this example, what i'm doing in my project is the same and completely based on the code in this example. But in my project when im trying to do
`const books: Books[] = action.payload;`
I would get this kind of error:
`Type 'string | Book | Book[]' is not assignable to type 'Book[]'. Type 'string' is not assignable to type 'Book'.`
